### ISSUE TITLE
custom RTE button

### ISSUE THREAD

**Issue by webernir** [lior2710/BE#3]
- default icon should be [file-code-o](http://fontawesome.io/icon/file-code-o/)
![image](https://cloud.githubusercontent.com/assets/2412543/26391461/8f2afff2-406b-11e7-8f62-363ba9589fca.png)

- should be configurable via props

@lior2710

**Comment by lior2710** [comment]
are you sure you want font awesome dependency?

**Comment by webernir** [comment]
@lior2710  it's an interesting point. i don't want that dependency in this package, but want to be able to _pass_ the icon. 
can we add ONLY a specific icon (include the svg in project files)?

**Comment by lior2710** [comment]
Thats what I had in mind...
Either have a hard-coded version of an icon (in svg or png) or just put a bootstrap glyp icon

**Comment by lior2710** [comment]
are you sure you don't want to simply use the old and good caret icon like all dropdowns have?

**Comment by webernir** [comment]
@lior2710 go with hard-coded version of an icon (in svg or png)

**Comment by lior2710** [comment]
ok got it
