### ISSUE TITLE
show border and RTE icon only on hover

### ISSUE THREAD

**Issue by webernir** [lior2710/BE#4]
@lior2710 the desired behavior is:
- when _not_ hovered, the field should look like a label
- when hovered, a border and an icon shows up

example:
![rtf-label](https://cloud.githubusercontent.com/assets/2412543/26436117/e830fed8-411c-11e7-9ab5-47d714cff830.gif)

**Comment by lior2710** [comment]
Well, this can be done by an external css.. And I do believe that is should.
But if you still want it, would you like it to be the default behavior?
If not, please mention the interface you would like to implement for it (css class? prop?).

**Comment by webernir** [comment]
@lior2710 this should be the default behavior. 
this is (one) of the components` purpose.
